<?php
include 'includes/ab_batch_example.batch.inc';

/*
 * Implementation of hook_menu()
 */
function ab_batch_example_menu() {
	$items = array();
	$items['admin/batch'] = array(
		'title' => 'The Batch API is so easy',
		'page callback' => 'ab_batch_example_page',
		'access callback' => TRUE,
		'type' => MENU_NORMAL_ITEM,
	);
	return $items;
}

function ab_batch_example_page() {
	return drupal_get_form('ab_batch_example_form');
}

function ab_batch_example_form($form, &$form_state) {
	$form = array();
	$form['options'] = array(
		'#type' => 'fieldset',
		'#title' => t('Rewrite Node Bodies'),
		'#weight' => 5,
		'#collapsible' => FALSE,
		'#collapsed' => FALSE,
	);
	$form['options']['bodytext'] = array(
	  '#type' => 'text_format',
		'#base_type' => 'textarea',
	  '#title' => t('Body Text'),
	  '#default_value' => t('Stuff goes here'),
		'#rows' => 4,
	  '#description' => t('Enter the new body text for all your nodes.'),
	);
	$form['options']['submit'] = array(
		'#type' => 'submit',
		'#value' => t('Go!')
	);
	
	return $form;
}

function ab_batch_example_form_validate($form, &$form_state) {
  // Validation logic.
}
function ab_batch_example_form_submit($form, &$form_state) {
  // Submission logic.
	ab_batch_example_start($form_state['values']['bodytext']['value']);
}

function _p($string) {
  error_log(print_r($string, 1), 0);
}

?>